create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  price numeric(12,2) not null,
  category_id bigint references public.categories(id),
  image_url text,
  stock integer default 10,
  rating numeric(3,1) default 4.5,
  created_at timestamptz not null default now()
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password text not null,
  role text not null default 'customer',
  cpf text,
  phone text,
  address text,
  avatar_url text default '/images/avatar-default.svg',
  secret_note text,
  idor_flag text,
  created_at timestamptz not null default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id),
  user_id bigint references public.users(id),
  author_name text,
  rating integer default 5,
  comment text,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id),
  status text default 'processando',
  total numeric(12,2) not null,
  shipping_address text,
  internal_note text,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity integer not null,
  price numeric(12,2) not null
);

create table if not exists public.support_tickets (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id),
  name text,
  email text,
  subject text,
  message text,
  status text default 'aberto',
  created_at timestamptz not null default now()
);

create table if not exists public.missions (
  id bigint generated by default as identity primary key,
  code text not null unique,
  title text not null,
  category text not null,
  difficulty text not null,
  description text not null,
  objective text not null,
  points integer not null default 100,
  sort_order integer default 0
);

create table if not exists public.flags (
  id bigint generated by default as identity primary key,
  mission_id bigint not null references public.missions(id) on delete cascade,
  flag_value text not null
);

create table if not exists public.lab_progress (
  id bigint generated by default as identity primary key,
  participant_id text not null,
  session_id text not null,
  handle text not null,
  mission_code text not null,
  solved_at timestamptz not null default now(),
  constraint lab_progress_participant_mission_key unique (participant_id, mission_code)
);

create table if not exists public.lab_presence (
  participant_id text primary key,
  handle text not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create or replace function public.vuln_login(email_input text, password_hash_input text)
returns table (
  id bigint,
  name text,
  email text,
  role text
)
language plpgsql
as $$
begin
  -- Intentionally vulnerable for the security lab.
  return query execute
    'select id, name, email, role from public.users where email = '''
    || email_input
    || ''' and password = '''
    || password_hash_input
    || ''' limit 1';
end;
$$;

grant execute on function public.vuln_login(text, text) to anon, authenticated, service_role;
